import Foundation

// Configures node-cost weighting for Viterbi path scoring.
nonisolated struct SegmenterScoring {
    let baseCost: Int
    let lengthReward: Int
    let singleCharacterPenalty: Int
    let deinflectionPenalty: Int
    let dictionaryBonus: Int
    let unknownSegmentPenalty: Int
    let posGoodTransitionBonus: Int
    let posBadTransitionPenalty: Int

    static let `default` = SegmenterScoring(
        baseCost: 10,
        lengthReward: 3,
        singleCharacterPenalty: 3,
        deinflectionPenalty: 2,
        dictionaryBonus: 6,
        unknownSegmentPenalty: 40,
        posGoodTransitionBonus: -50,
        posBadTransitionPenalty: 150
    )

    // MARK: - Viterbi scoring constants (not yet wired into the active segmentation path)

    static let viterbiDictionaryBonus = -3
    static let viterbiSingleCharacterPenalty = 3
    static let viterbiNonFunctionalSingleCharacterPenalty = 12
    static let viterbiUnknownPenalty = 6
    static let viterbiLengthRewardPerCharacter = -6
    static let viterbiVerbBonus = -3
    // Penalty applied to multi-char dict entries that decompose into prefix + grammatical kana
    // (e.g. たいよ = たい + よ, 生まれた = 生まれ + た). Pushes Viterbi toward the compositional
    // path so auxiliaries and sentence-final particles don't get absorbed into the verb stem.
    static let viterbiBundledGrammaticalEndingPenalty = 15

    // Trailing kana that signal "this surface ends with a grammatical particle/auxiliary fused
    // onto its stem" — checked at lattice-build time, not at every transition lookup.
    static let grammaticalEndingKana: Set<Character> = ["た", "だ", "て", "で", "よ"]

    // POS-bigram costs. Negative values are *rewards* (push the path toward this pairing);
    // positive values are *penalties* (push the path away). Constant *names* describe sign
    // (Reward / Penalty) — when re-calibrating, if the empirical sign flips, rename the
    // constant so the dispatch in transitionCost stays readable.
    //
    // Values below were generated by Scripts/calibration/calibrate_viterbi_costs.py from
    // IPADic's CRF-trained matrix.bin: for each POS-class bigram bucket, we take the
    // median connection cost over every (right_id ∈ prev_bucket, left_id ∈ next_bucket)
    // cell, then divide by 100 to land in the same magnitude band as the node-cost
    // constants above. Inline comments show raw IPADic-scale medians and sample size (n).
    //
    // To disable the expanded table and revert to a leaner heuristic: gate the new branches
    // in transitionCost(prev:next:) on a flag, or revert this file. The Viterbi pathway
    // itself is gated by SegmenterSettings.isViterbiEnabled — turning that off bypasses
    // transitionCost entirely (greedy longest-match does not consult bigram costs).

    // --- "Original 9" buckets, now empirically calibrated. Some sign-flipped vs the
    //     original hand-tuned values; renamed where that happened. ---
    static let viterbiParticleParticlePenalty = 1        // raw 142   (n=49284)
    static let viterbiPrefixParticlePenalty = 13         // raw 1319  (n=888)
    static let viterbiCounterParticleReward = -26        // raw -2579 (n=222) — flipped from "Penalty"
    static let viterbiNounNounPenalty = 1                // raw 139   (n=1024)
    static let viterbiNounParticleReward = -24           // raw -2416 (n=7104)
    static let viterbiAdjParticleReward = -4             // raw -425  (n=30192)
    static let viterbiVerbAuxiliaryReward = -16          // raw -1643 (n=133920)
    static let viterbiVerbParticleReward = -4            // raw -443  (n=159840)
    static let viterbiParticleNounPenalty = 6            // raw 560   (n=7104)  — flipped from "Reward"

    // --- Rewards (negative). ---
    static let viterbiPrefixNounReward = -10             // raw -1043 (n=128)
    static let viterbiNumericCounterReward = -107        // raw -10731 (n=1) — single matched cell; strong signal
    static let viterbiNounSuffixReward = -27             // raw -2734 (n=288)
    static let viterbiNounAuxiliaryReward = -7           // raw -722  (n=5952)
    static let viterbiAdjectiveAuxiliaryReward = -4      // raw -437  (n=25296)
    static let viterbiAuxiliaryAuxiliaryReward = -11     // raw -1134 (n=34596)
    static let viterbiCopulaParticleReward = -4          // raw -372  (n=41292)
    static let viterbiCopulaAuxiliaryReward = -11        // raw -1134 (n=34596) — same cells as aux-aux (IPADic collapse)
    static let viterbiPronounParticleReward = -24        // raw -2374 (n=444)
    static let viterbiProperNounParticleReward = -24     // raw -2353 (n=1554)
    static let viterbiParticleVerbReward = -4            // raw -383  (n=159840)
    static let viterbiAdverbAdverbReward = -1            // raw -62   (n=4)
    static let viterbiPrefixPrefixReward = -3            // raw -289  (n=16)  — flipped from "Penalty"

    // --- Near-neutral (kept for documentation; mostly noise vs node costs). ---
    static let viterbiAdverbAdjectiveCost = 0            // raw 36    (n=272)
    static let viterbiParticleAdjectiveCost = 1          // raw 98    (n=30192)

    // --- Penalties (positive). Names flipped where sign reversed. ---
    static let viterbiAdverbVerbPenalty = 4              // raw 374   (n=1440)  — flipped from "Reward"
    static let viterbiNounVerbCompoundPenalty = 4        // raw 445   (n=23040) — flipped from "Reward"; suru-compounds use special context IDs MeCab handles via node cost, not bigram
    static let viterbiAdjectiveNounPenalty = 5           // raw 529   (n=4352)  — flipped from "Reward"
    static let viterbiInterjectionParticlePenalty = 4    // raw 419   (n=222)   — flipped from "Reward"
    static let viterbiConjunctionAnyPenalty = 3          // raw 311   (n=2630)  — flipped from "Reward"
    static let viterbiAuxiliaryVerbPenalty = 7           // raw 748   (n=133920)
    static let viterbiAuxiliaryNounPenalty = 9           // raw 948   (n=5952)
    static let viterbiAuxiliaryAdjectivePenalty = 5      // raw 527   (n=25296)
    static let viterbiPrefixVerbPenalty = 1              // raw 132   (n=2880)
    static let viterbiPrefixAuxiliaryPenalty = 4         // raw 404   (n=744)
    static let viterbiSuffixVerbPenalty = 6              // raw 594   (n=6480)
    static let viterbiSuffixNounPenalty = 6              // raw 643   (n=288)
    static let viterbiCopulaVerbPenalty = 7              // raw 748   (n=133920) — same cells as aux-verb
    static let viterbiCopulaNounPenalty = 9              // raw 948   (n=5952)   — same cells as aux-noun
    static let viterbiParticleAuxiliaryPenalty = 10      // raw 1023  (n=41292)

    // Calculates edge-local node cost independent of predecessor transitions.
    static func edgeCost(_ edge: LatticeEdge) -> Int {
        var cost = 0

        if edge.isDictionaryMatch {
            cost += viterbiDictionaryBonus
        }

        if edge.surface.count == 1 {
            cost += viterbiSingleCharacterPenalty + 5
            if !PartOfSpeech.isParticle(edge.partOfSpeech)
                && !PartOfSpeech.isAuxiliary(edge.partOfSpeech)
                && !isPunctuationSurface(edge.surface) {
                cost += viterbiNonFunctionalSingleCharacterPenalty
            }
        }

        if !edge.isDictionaryMatch {
            cost += viterbiUnknownPenalty
        }

        cost += edge.surface.count * viterbiLengthRewardPerCharacter

        // Only reward "true verb" entries — those tagged verb and not also noun. Multi-POS
        // entries like たいよ (noun+verb) and other compound nouns get noun-ish treatment so
        // they don't outrank legitimate compositional parses.
        if PartOfSpeech.isVerb(edge.partOfSpeech) && !PartOfSpeech.isNoun(edge.partOfSpeech) {
            cost += viterbiVerbBonus
        }

        if edge.decomposesAtGrammaticalEnding {
            cost += viterbiBundledGrammaticalEndingPenalty
        }

        return cost
    }

    // Detects punctuation-only single-character surfaces so they avoid strong lexical penalties.
    private static func isPunctuationSurface(_ surface: String) -> Bool {
        guard surface.count == 1 else { return false }
        for scalar in surface.unicodeScalars {
            if CharacterSet.punctuationCharacters.contains(scalar)
                || CharacterSet.symbols.contains(scalar)
                || CharacterSet.whitespacesAndNewlines.contains(scalar) { continue }
            return false
        }
        return true
    }

    // Primary transition-cost entry point used by Viterbi. When BOTH adjacent edges have
    // IPADic context IDs (populated at dict-build time, see Resources/migrate_add_context_ids.py),
    // we look up the bigram cost directly in IPADic's matrix.bin — same fidelity as MeCab.
    // Otherwise we fall through to the POS-class bucket dispatch below, which uses the empirical
    // medians produced by Scripts/calibration/calibrate_viterbi_costs.py. The matrix path
    // divides by 100 to land in the same scale as the bucketed values + the existing node
    // costs (which are also at /100 scale).
    static func transitionCost(prev: LatticeEdge, next: LatticeEdge) -> Int {
        if let prevRight = prev.ipadicRightID, let nextLeft = next.ipadicLeftID {
            let raw = IPADicMatrix.shared.cost(rightID: prevRight, leftID: nextLeft)
            return raw / 100
        }
        return transitionCost(prev: prev.partOfSpeech, next: next.partOfSpeech)
    }

    // POS-class bucket fallback. Used when one or both adjacent edges lack IPADic context IDs
    // (deinflected surfaces that weren't tagged, fallback edges for unknown text, or older
    // dictionaries built before migrate_add_context_ids.py ran). Rules dispatch in priority
    // order; the first matching rule wins so the most distinctive bigrams (numeric+counter,
    // aux chains) get checked before the broader ones (any-noun, any-particle).
    static func transitionCost(prev: UInt64, next: UInt64) -> Int {
        if prev == 0 || next == 0 { return 0 }

        // --- Highest-confidence pairings (rare bigrams with very tight semantics) ---
        if PartOfSpeech.isNumeric(prev)   && PartOfSpeech.isCounter(next)   { return viterbiNumericCounterReward }
        if PartOfSpeech.isAuxiliary(prev) && PartOfSpeech.isAuxiliary(next) { return viterbiAuxiliaryAuxiliaryReward }

        // --- Penalties for syntactically broken pairings ---
        if PartOfSpeech.isPrefix(prev)    && PartOfSpeech.isAuxiliary(next) { return viterbiPrefixAuxiliaryPenalty }
        if PartOfSpeech.isAuxiliary(prev) && PartOfSpeech.isVerb(next)      { return viterbiAuxiliaryVerbPenalty }
        if PartOfSpeech.isAuxiliary(prev) && PartOfSpeech.isNoun(next)      { return viterbiAuxiliaryNounPenalty }
        if PartOfSpeech.isAuxiliary(prev) && PartOfSpeech.isAdjective(next) { return viterbiAuxiliaryAdjectivePenalty }
        if PartOfSpeech.isCopula(prev)    && PartOfSpeech.isVerb(next)      { return viterbiCopulaVerbPenalty }
        if PartOfSpeech.isCopula(prev)    && PartOfSpeech.isNoun(next)      { return viterbiCopulaNounPenalty }
        if PartOfSpeech.isSuffix(prev)    && PartOfSpeech.isVerb(next)      { return viterbiSuffixVerbPenalty }
        if PartOfSpeech.isSuffix(prev)    && PartOfSpeech.isNoun(next)      { return viterbiSuffixNounPenalty }
        if PartOfSpeech.isPrefix(prev)    && PartOfSpeech.isVerb(next)      { return viterbiPrefixVerbPenalty }
        if PartOfSpeech.isParticle(prev)  && PartOfSpeech.isAuxiliary(next) { return viterbiParticleAuxiliaryPenalty }

        // --- Empirically sign-flipped pairings — my hand-tuned guesses had these wrong ---
        if PartOfSpeech.isAdverb(prev)    && PartOfSpeech.isVerb(next)      { return viterbiAdverbVerbPenalty }
        if PartOfSpeech.isNoun(prev)      && PartOfSpeech.isVerb(next)      { return viterbiNounVerbCompoundPenalty }
        if PartOfSpeech.isAdjective(prev) && PartOfSpeech.isNoun(next)      { return viterbiAdjectiveNounPenalty }
        if PartOfSpeech.isInterjection(prev) && PartOfSpeech.isParticle(next) { return viterbiInterjectionParticlePenalty }
        if PartOfSpeech.isPrefix(prev)    && PartOfSpeech.isPrefix(next)    { return viterbiPrefixPrefixReward }
        if PartOfSpeech.isCounter(prev)   && PartOfSpeech.isParticle(next)  { return viterbiCounterParticleReward }

        // --- Original-bucket rules (now empirically valued) ---
        if PartOfSpeech.isParticle(prev) && PartOfSpeech.isParticle(next) { return viterbiParticleParticlePenalty }
        if PartOfSpeech.isPrefix(prev)   && PartOfSpeech.isParticle(next) { return viterbiPrefixParticlePenalty }
        if PartOfSpeech.isVerb(prev)     && PartOfSpeech.isAuxiliary(next) { return viterbiVerbAuxiliaryReward }
        if PartOfSpeech.isVerb(prev)     && PartOfSpeech.isParticle(next) { return viterbiVerbParticleReward }

        // --- Rewards for high-frequency, natural pairings ---
        if PartOfSpeech.isCopula(prev)    && PartOfSpeech.isAuxiliary(next) { return viterbiCopulaAuxiliaryReward }
        if PartOfSpeech.isCopula(prev)    && PartOfSpeech.isParticle(next)  { return viterbiCopulaParticleReward }
        if PartOfSpeech.isPrefix(prev)    && PartOfSpeech.isNoun(next)      { return viterbiPrefixNounReward }
        if PartOfSpeech.isNoun(prev)      && PartOfSpeech.isSuffix(next)    { return viterbiNounSuffixReward }
        if PartOfSpeech.isNoun(prev)      && PartOfSpeech.isAuxiliary(next) { return viterbiNounAuxiliaryReward }
        if PartOfSpeech.isAdjective(prev) && PartOfSpeech.isAuxiliary(next) { return viterbiAdjectiveAuxiliaryReward }
        if PartOfSpeech.isAdverb(prev)    && PartOfSpeech.isAdjective(next) { return viterbiAdverbAdjectiveCost }
        if PartOfSpeech.isAdverb(prev)    && PartOfSpeech.isAdverb(next)    { return viterbiAdverbAdverbReward }
        if PartOfSpeech.isProperNoun(prev) && PartOfSpeech.isParticle(next) { return viterbiProperNounParticleReward }
        if PartOfSpeech.isPronoun(prev)   && PartOfSpeech.isParticle(next)  { return viterbiPronounParticleReward }
        if PartOfSpeech.isConjunction(prev) { return viterbiConjunctionAnyPenalty }
        if PartOfSpeech.isParticle(prev)  && PartOfSpeech.isVerb(next)      { return viterbiParticleVerbReward }
        if PartOfSpeech.isParticle(prev)  && PartOfSpeech.isAdjective(next) { return viterbiParticleAdjectiveCost }

        // --- Broad fallbacks (kept last so specific rules above always win) ---
        if PartOfSpeech.isNoun(prev)      && PartOfSpeech.isNoun(next)      { return viterbiNounNounPenalty }
        if PartOfSpeech.isNoun(prev)      && PartOfSpeech.isParticle(next)  { return viterbiNounParticleReward }
        if PartOfSpeech.isAdjective(prev) && PartOfSpeech.isParticle(next)  { return viterbiAdjParticleReward }
        if PartOfSpeech.isParticle(prev)  && PartOfSpeech.isNoun(next)      { return viterbiParticleNounPenalty }

        return 0
    }
}
