// Generated by scripts/generate_kyujitai_table.py — do not edit by hand.
// Source: https://raw.githubusercontent.com/BYVoid/OpenCC/6aa8c54e100678150985a9af631359f80e31956a/data/dictionary/JPShinjitaiCharacters.txt
// SHA-256: 12cec7250b873ef52b36d8f92218d4f92c0aaf5d8cd7c58fe42d9785bdcdc43a
// Re-run the script after changing the "opencc-jp-shinjitai" entry in Resources/data-manifest.json.

// Old-form kanji paired with the modern form each normalizes to, for KyujitaiNormalizer.
nonisolated enum KyujitaiTable {
    // 412 pairs stored flat: each pair is the old-form character immediately followed by
    // its modern form, so the string reads old, new, old, new, ...; line breaks are ignored.
    static let flatPairs = """
        乘乗亂乱亙亘亞亜佛仏來来俠侠俱倶倂併值値假仮傳伝僞偽價価儉倹兒児兔兎內内兩両冰氷凛凜剎刹剩剰劍剣
        劑剤勞労勳勲勵励勸勧勻匀區区卷巻卻却卽即參参吳呉咒呪啞唖單単噓嘘嚙噛嚴厳囑嘱圈圏國国圍囲圓円圖図
        團団堯尭填塡增増墮堕壓圧壘塁壞壊壤壌壯壮壹壱壽寿奧奥奬奨妝粧姊姉姬姫孃嬢學学寢寝實実寫写寬寛寶宝
        將将專専對対屆届屬属峯峰峽峡嶋島嶌島嶽岳巖巌巢巣帶帯廁厠廢廃廣広廳庁彈弾彌弥彎弯彥彦徑径從従徵徴
        德徳恆恒悅悦惠恵惡悪惱悩愼慎慘惨應応懷懐戀恋戰戦戲戯戶戸戾戻拂払拔抜拜拝挾挟插挿揭掲搔掻搖揺搜捜
        摑掴擇択擊撃擔担據拠擧挙擴拡攝摂攪撹收収效効敍叙敕勅敘叙數数斷断晄晃晉晋晚晩晝昼暨曁曆暦曉暁曾曽
        會会枡桝查査條条棧桟棱稜榆楡榮栄槇槙槪概樂楽樓楼樞枢樣様橫横檜桧檢検櫻桜權権歐欧歡歓步歩歲歳歷歴
        歸帰殘残殼殻毆殴每毎氣気污汚沒没涉渉淚涙淨浄淺浅渴渇溪渓溫温溼湿滯滞滿満潑溌潛潜澀渋澁渋澤沢濕湿
        濟済濤涛濱浜濾沪瀧滝瀨瀬灣湾焰焔燈灯燒焼營営爐炉爭争爲為牀床犧犠狀状狹狭獎奨獨独獵猟獸獣獻献瓣弁
        甁瓶產産畫画當当疊畳痹痺瘦痩癡痴發発皋皐盜盗盡尽眞真硏研碎砕礪砺祕秘祿禄禦御禪禅禮礼禰祢禱祷稅税
        稱称稻稲穎頴穗穂穩穏穰穣竈竃竊窃竝並粹粋糉粽絕絶絲糸經経綠緑緖緒緣縁縣県縱縦總総繡繍繩縄繪絵繫繋
        繼継續続纔才纖繊缺欠罐缶羣群聯連聰聡聲声聽聴肅粛脣唇脫脱腦脳腳脚膽胆臟臓臺台與与舉挙舊旧舍舎舖舗
        艷艶荔茘莊荘莖茎菸煙萊莱萠萌萬万蔣蒋蔥葱薰薫藏蔵藝芸藥薬蘆芦處処虛虚號号螢蛍蟬蝉蟲虫蠟蝋蠶蚕蠻蛮
        衞衛裝装襃褒覺覚覽覧觀観觸触說説謠謡證証譯訳譽誉讀読變変讓譲豐豊豫予貓猫貳弐賣売賴頼贊賛贗贋踐践
        輕軽輛輌轉転辨弁辭辞辯弁遙遥遞逓遲遅邊辺郞郎鄉郷鄕郷鄰隣醉酔醫医醬醤醱醗釀醸釋釈銳鋭鋪舗錄録錢銭
        鍊錬鎭鎮鐵鉄鑄鋳鑛鉱閱閲關関陷陥隨随險険隱隠雙双雜雑雞鶏霸覇靈霊靜静顏顔顯顕飜翻餘余餠餅騷騒驅駆
        驗験驛駅髓髄體体髮髪鬥闘鬪闘鬭闘鱉鼈鷄鶏鷗鴎鹼鹸鹽塩麥麦麪麺麴麹麵麺黃黄黑黒默黙點点黨党齊斉齋斎
        齒歯齡齢龍竜龜亀
        """
}
