import Foundation

// Derived data attached to a Note: the LLM-produced line-by-line breakdown of a song's lyrics.
// Cached in SongBreakdownStore; never written into the Note itself per AGENTS.md Note Persistence rule.
// Cache key is sourceTextHash; mismatched hash on read marks the breakdown stale and surfaces
// a Regenerate banner without auto-invalidating.
struct SongBreakdown: Codable, Equatable, Sendable {
    static let currentSchemaVersion: Int = 1

    let noteID: UUID
    let sourceTextHash: String
    let generatedAt: Date
    let provider: SongBreakdownProvider
    let lines: [SongLine]
    let schemaVersion: Int

    init(
        noteID: UUID,
        sourceTextHash: String,
        generatedAt: Date,
        provider: SongBreakdownProvider,
        lines: [SongLine],
        schemaVersion: Int = SongBreakdown.currentSchemaVersion
    ) {
        self.noteID = noteID
        self.sourceTextHash = sourceTextHash
        self.generatedAt = generatedAt
        self.provider = provider
        self.lines = lines
        self.schemaVersion = schemaVersion
    }
}

// A single word entry within a line's breakdown.
// `sungRomaji` captures the actually-sung pronunciation, which may differ from the canonical
// dictionary reading (e.g. 愛人 written, "hito" sung). When the user taps the chip to save,
// `surface` is resolved against the dictionary to obtain a canonical_entry_id —
// the (surface, sungRomaji) pair is a lookup key, not authoritative identity.
//
// Deliberately NOT Identifiable: a single line can list the same word more than once
// (chorus refrains, repeated particles), so any identity derived from the value alone
// collides and breaks SwiftUI ForEach. Consumers iterate with positional identity instead
// (e.g. ForEach over enumerated() with id: \.offset).
struct SongWord: Codable, Equatable, Sendable {
    let surface: String
    let sungRomaji: String
    let definition: String
}

// Encodes "this line repeats an earlier one" so the stepper can render a chip linking back
// without duplicating the full breakdown. The prompt emits two forms:
//   1. "= line N"   →  .sameAsLine(N)
//   2. "Parallel to line N with substitution: X → Y"  →  .parallelTo(line: N, substitution: "X → Y")
enum LineReference: Codable, Equatable, Sendable {
    case sameAsLine(Int)
    case parallelTo(line: Int, substitution: String)
}

// Records which provider produced a breakdown so the cache can show diagnostics
// (e.g. "generated by Claude on 2026-05-14"). Independent of LLMProvider in Settings
// so future provider additions don't leak into the cache schema.
enum SongBreakdownProvider: String, Codable, Sendable {
    case stub
    case openAI = "openai"
    case claude = "claude"

    var displayName: String {
        switch self {
        case .stub: return "Stub"
        case .openAI: return "OpenAI"
        case .claude: return "Claude"
        }
    }
}
