#!/usr/bin/env python3
# One-shot migration: add + populate the entry_jlpt_level table on an already-built
# dictionary.sqlite, WITHOUT the full ~30-min rebuild (JMdict parse, MeCab, FTS reindex).
#
# The full builder (generate_db.py) calls the SAME import_jlpt_levels function, so this
# produces byte-for-byte the JLPT data a clean rebuild would. Re-runnable: import_jlpt_levels
# drops and repopulates the table each time.
#
# Input: Resources/jlpt-vocab.tsv (generated by scripts/build_jlpt_vocab_tsv.py from the
# Tanos / Jonathan Waller CC BY JLPT lists).
#
# Usage:
#   python3 Resources/migrate_add_jlpt_levels.py
import sqlite3
import sys
import time
from pathlib import Path

import generate_db as g

DB_PATH = Path(__file__).resolve().parent / "dictionary.sqlite"


def main():
    if not DB_PATH.exists():
        sys.exit(f"dictionary.sqlite not found at {DB_PATH} — run generate_db.py first")

    start = time.time()
    conn = sqlite3.connect(str(DB_PATH))
    print(f"Adding JLPT levels to {DB_PATH.name}...")

    g.import_jlpt_levels(conn)

    conn.commit()
    conn.execute("ANALYZE")
    conn.execute("PRAGMA optimize")
    conn.close()
    print(f"Done in {time.time() - start:.1f}s")


if __name__ == "__main__":
    main()
