#!/usr/bin/env python3
# Generates Kioku/Dictionary/KyujitaiTable.swift: the old-form (kyujitai / variant) kanji to
# modern-form (shinjitai) table that SpellingNormalizer applies in the trie and in dictionary lookup.
#
# Source: OpenCC's JPShinjitaiCharacters.txt (Apache-2.0), pinned by commit and SHA-256 in
# Resources/data-manifest.json under "opencc-jp-shinjitai". It lists, per modern character, the old
# forms that map to it. KANJIDIC2 breaks ties when one old form maps to several modern ones: the
# Jouyou kanji (grades 1-8) wins, then Jinmeiyou (9-10), then file order. Both are fetched from
# upstream into generate_db.py's temporary work folder for the run and deleted afterwards.
#
# Usage: python3 scripts/generate_kyujitai_table.py
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "Resources" / "data-manifest.json"
sys.path.insert(0, str(ROOT / "Resources"))
import generate_db  # noqa: E402
OUTPUT = ROOT / "Kioku" / "Dictionary" / "KyujitaiTable.swift"

# Legitimate variant spellings of common kanji that OpenCC's table lacks as keys. Each maps to the
# modern form named beside it: 鬪 and 舖 are older variants of 闘 and 舗; 嶌 and 嶋 are variants of 島.
SUPPLEMENTAL_PAIRS = {"鬪": "闘", "舖": "舗", "嶌": "島", "嶋": "島"}


# Downloads the pinned OpenCC table into the run's work folder; generate_db.fetch_archive verifies
# its SHA-256 against the manifest.
def fetch_opencc_table():
    entry = generate_db.load_manifest()["opencc-jp-shinjitai"]
    path = generate_db.fetch_archive(entry)
    return path, entry["fetch"]["url"], entry["fetch"]["archiveSha256"]


# Ranks a candidate modern form for tie-breaking: 0 for Jouyou kanji, 1 for Jinmeiyou, 2 otherwise.
def rank_by_grade(grades, character):
    grade = grades.get(character)
    if grade is not None and 1 <= grade <= 8:
        return 0
    if grade in (9, 10):
        return 1
    return 2


# Builds the old -> new mapping from the OpenCC table, resolving one-to-many cases by KANJIDIC2 grade.
def build_mapping(opencc_path):
    generate_db.materialize_source(generate_db.load_manifest()["kanjidic2-all"])
    characters = json.load(open(generate_db.KANJIDIC2_PATH, encoding="utf-8"))["characters"]
    grades = {c["literal"]: (c.get("misc") or {}).get("grade") for c in characters}

    candidates = {}
    for line in open(opencc_path, encoding="utf-8"):
        if not line.strip() or line.startswith("#"):
            continue
        modern, olds = line.rstrip("\n").split("\t", 1)
        for old in olds.split():
            if len(old) == 1 and len(modern) == 1 and old != modern:
                candidates.setdefault(old, []).append(modern)

    mapping = {old: min(moderns, key=lambda m: rank_by_grade(grades, m)) for old, moderns in candidates.items()}
    for old, modern in SUPPLEMENTAL_PAIRS.items():
        mapping.setdefault(old, modern)

    chained = set(mapping) & set(mapping.values())
    if chained:
        sys.exit(f"old forms that are also targets (chains would need two passes): {sorted(chained)}")
    return mapping


# Writes the generated Swift source: every pair as "old" then "new" in one flat string.
def write_swift(mapping, source_url, source_sha):
    lines = []
    ordered = sorted(mapping.items())
    for start in range(0, len(ordered), 24):
        lines.append("".join(old + new for old, new in ordered[start:start + 24]))
    body = "\n".join("        " + line for line in lines)
    OUTPUT.write_text(
        f"""// Generated by scripts/generate_kyujitai_table.py — do not edit by hand.
// Source: {source_url}
// SHA-256: {source_sha}
// Re-run the script after changing the "opencc-jp-shinjitai" entry in Resources/data-manifest.json.

// Old-form kanji paired with the modern form each normalizes to, for SpellingNormalizer.
nonisolated enum KyujitaiTable {{
    // {len(mapping)} pairs stored flat: each pair is the old-form character immediately followed by
    // its modern form, so the string reads old, new, old, new, ...; line breaks are ignored.
    static let flatPairs = \"\"\"
{body}
        \"\"\"
}}
""",
        encoding="utf-8",
    )


# Entry point: fetch, resolve, write.
def main():
    generate_db.open_work_dir()
    try:
        path, url, digest = fetch_opencc_table()
        mapping = build_mapping(path)
    finally:
        generate_db.close_work_dir()
    write_swift(mapping, url, digest)
    print(f"Wrote {len(mapping)} pairs -> {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
