#!/usr/bin/env python3
# Generates Kioku/Dictionary/KyujitaiTable.swift: the old-form (kyujitai / variant) kanji to
# modern-form (shinjitai) table that KyujitaiNormalizer applies in the trie and in dictionary lookup.
#
# Source: OpenCC's JPShinjitaiCharacters.txt (Apache-2.0), pinned by commit and SHA-256 in
# Resources/data-manifest.json under "opencc-jp-shinjitai". It lists, per modern character, the old
# forms that map to it. KANJIDIC2 (Resources/kanjidic2-all.json, fetched by
# `python3 Resources/generate_db.py --sources-only`) breaks ties when one old form maps to several
# modern ones: the Jouyou kanji (grades 1-8) wins, then Jinmeiyou (9-10), then file order.
#
# Usage: python3 scripts/generate_kyujitai_table.py
import hashlib
import json
import os
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "Resources" / "data-manifest.json"
KANJIDIC2 = ROOT / "Resources" / "kanjidic2-all.json"
# Shared with Resources/generate_db.py: outside the checkout so it survives disposable worktrees.
CACHE = Path(os.environ.get("KIOKU_SOURCE_CACHE") or Path.home() / "Projects" / "kioku-source-cache")
OUTPUT = ROOT / "Kioku" / "Dictionary" / "KyujitaiTable.swift"

# Legitimate variant spellings of common kanji that OpenCC's table lacks as keys. Each maps to the
# modern form named beside it: 鬪 and 舖 are older variants of 闘 and 舗; 嶌 and 嶋 are variants of 島.
SUPPLEMENTAL_PAIRS = {"鬪": "闘", "舖": "舗", "嶌": "島", "嶋": "島"}


# Downloads the pinned OpenCC table into the source cache when absent and verifies its SHA-256.
def fetch_opencc_table():
    entry = next(e for e in json.load(open(MANIFEST, encoding="utf-8"))["resources"] if e["name"] == "opencc-jp-shinjitai")
    fetch = entry["fetch"]
    path = CACHE / fetch["cacheName"]
    if not path.exists():
        CACHE.mkdir(parents=True, exist_ok=True)
        request = urllib.request.Request(fetch["url"], headers={"User-Agent": "Kioku-table-generator"})
        path.write_bytes(urllib.request.urlopen(request, timeout=60).read())
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    if digest != fetch["archiveSha256"]:
        sys.exit(f"{path.name}: sha256 {digest} != pinned {fetch['archiveSha256']}")
    return path, fetch["url"], digest


# Ranks a candidate modern form for tie-breaking: 0 for Jouyou kanji, 1 for Jinmeiyou, 2 otherwise.
def rank_by_grade(grades, character):
    grade = grades.get(character)
    if grade is not None and 1 <= grade <= 8:
        return 0
    if grade in (9, 10):
        return 1
    return 2


# Builds the old -> new mapping from the OpenCC table, resolving one-to-many cases by KANJIDIC2 grade.
def build_mapping(opencc_path):
    if not KANJIDIC2.exists():
        sys.exit("Resources/kanjidic2-all.json is missing — run: python3 Resources/generate_db.py --sources-only")
    characters = json.load(open(KANJIDIC2, encoding="utf-8"))["characters"]
    grades = {c["literal"]: (c.get("misc") or {}).get("grade") for c in characters}

    candidates = {}
    for line in open(opencc_path, encoding="utf-8"):
        if not line.strip() or line.startswith("#"):
            continue
        modern, olds = line.rstrip("\n").split("\t", 1)
        for old in olds.split():
            if len(old) == 1 and len(modern) == 1 and old != modern:
                candidates.setdefault(old, []).append(modern)

    mapping = {old: min(moderns, key=lambda m: rank_by_grade(grades, m)) for old, moderns in candidates.items()}
    for old, modern in SUPPLEMENTAL_PAIRS.items():
        mapping.setdefault(old, modern)

    chained = set(mapping) & set(mapping.values())
    if chained:
        sys.exit(f"old forms that are also targets (chains would need two passes): {sorted(chained)}")
    return mapping


# Writes the generated Swift source: every pair as "old" then "new" in one flat string.
def write_swift(mapping, source_url, source_sha):
    lines = []
    ordered = sorted(mapping.items())
    for start in range(0, len(ordered), 24):
        lines.append("".join(old + new for old, new in ordered[start:start + 24]))
    body = "\n".join("        " + line for line in lines)
    OUTPUT.write_text(
        f"""// Generated by scripts/generate_kyujitai_table.py — do not edit by hand.
// Source: {source_url}
// SHA-256: {source_sha}
// Re-run the script after changing the "opencc-jp-shinjitai" entry in Resources/data-manifest.json.

// Old-form kanji paired with the modern form each normalizes to, for KyujitaiNormalizer.
nonisolated enum KyujitaiTable {{
    // {len(mapping)} pairs stored flat: each pair is the old-form character immediately followed by
    // its modern form, so the string reads old, new, old, new, ...; line breaks are ignored.
    static let flatPairs = \"\"\"
{body}
        \"\"\"
}}
""",
        encoding="utf-8",
    )


# Entry point: fetch, resolve, write.
def main():
    path, url, digest = fetch_opencc_table()
    mapping = build_mapping(path)
    write_swift(mapping, url, digest)
    print(f"Wrote {len(mapping)} pairs -> {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
